### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by luckydog11** [DaiShiResearch/TransNeXt#1]
./classification/transnext_native.py, when I run it:
line 52, in get_relative_position_cpb
    axis_kh = F.adaptive_avg_pool1d(axis_qh.unsqueeze(0), key_size[0]).squeeze(0)
RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument #1 'self' (while checking arguments for adaptive_avg_pool1d)
axis_qh is a  2-dimensional tensor.

**Comment by DaiShiResearch** [comment]
May I inquire about your PyTorch version? 
In my tests, 'F.adaptive_avg_pool1d' can accept a 2-D tensor. The PyTorch version I used for testing is 2.0.0.

I have tested the following code:

```python
print(F.adaptive_avg_pool1d(torch.ones(1,56), 7))
```

The output is: `tensor([[1., 1., 1., 1., 1., 1., 1.]])`

In the code, `axis_qh.unsqueeze(0)` is a 2-D tensor, which is correct. After `avg_pool1d` outputs, adding `squeeze(0)` will restore the result to a 1-D tensor. This is consistent with the expected behavior.

**Comment by athrunsunny** [comment]
Maybe you can replace it with this code：
    axis_qh = torch.arange(query_size[0], dtype=torch.float32, device=device)
    axis_kh = F.adaptive_avg_pool1d(axis_qh.unsqueeze(0).unsqueeze(0), key_size[0]).squeeze(0).squeeze(0)
    axis_qw = torch.arange(query_size[1], dtype=torch.float32, device=device)
    axis_kw = F.adaptive_avg_pool1d(axis_qw.unsqueeze(0).unsqueeze(0), key_size[1]).squeeze(0).squeeze(0)
in PyTorch version 1.X

**Comment by MaoFuyou** [comment]
I want to get a relatively complete project about classification(such as train, test, utils and so on) to study more for your model!
