### ISSUE TITLE
Questions about the theory in the article

### ISSUE THREAD

**Issue by 895318** [DaiShiResearch/TransNeXt#6]
What is the meaning of learnable key in positional attention, I never understood this concept. Where does the learnable key come from? Is it an initial set of vectors to initialize the key? Is it an initial set of vectors that initialize the key? And what is the key updated based on?

I hope I can get your answer, thanks!

**Comment by 895318** [comment]
From the original Positional attention in section 3.1.2：An alternative approach to information aggregation is the use of **a set of learnable keys** that interact with queries originating from the input to obtain attention weights, i.e., Query-Learnable-Value (QLV) attention.

**Comment by DaiShiResearch** [comment]
As mentioned in section 3.1.2, this set of learnable keys is randomly initialized and obtained through data training. Since QLV attention disrupts the one-to-one correspondence between Key and Value, this QLV attention mechanism essentially learns a kind of implicit relative positional information, and its affinity matrix weights can dynamically change based on the current query vector, so it is still a special kind of attention mechanism.
