### ISSUE TITLE
Thanks for u works, i have a small question as below.

### ISSUE THREAD

**Issue by Fortuneteller6** [DaiShiResearch/TransNeXt#9]
How the Attention Map in fig 7 and Effective Receptive Field fig 8 can be drawn. Thanks again.

**Comment by DaiShiResearch** [comment]
To visualize the Effective Receptive Field (ERF), please refer to the RepLKNet work. For visualizing Attention, refer to the DINO work. We followed their methods with some distinctions:

1. **ERF Visualization**: We used a resolution of 224x224 instead of the 1024x1024 resolution used in works like RepLKNet. There are two reasons for this choice:
   - We observed that these classification models perform poorly in inference at ultra-high resolutions for IN-1K. For instance, RepLKNet-31B achieves only 0.9% accuracy (ImageNet-1K has only 1000 classes in total) beyond a resolution of 640x640, indicating complete model failure. Such demonstrations are significantly detached from practical applications.
   - At such large resolutions for visualization, the blocky artifacts on ERF become as small as individual pixels, making them difficult to perceive. Please refer to the visualization results on our GitHub homepage and in our paper for more details.

2. **Attention Visualization**: We do not employ the CLS token but use the query at the center of the image for visualization. The specific methodology and formulas are thoroughly explained beneath Figure 7 in our paper.

**Comment by Fortuneteller6** [comment]
> To visualize the Effective Receptive Field (ERF), please refer to the RepLKNet work. For visualizing Attention, refer to the DINO work. We followed their methods with some distinctions:
> 
> 1. **ERF Visualization**: We used a resolution of 224x224 instead of the 1024x1024 resolution used in works like RepLKNet. There are two reasons for this choice:
>    
>    * We observed that these classification models perform poorly in inference at ultra-high resolutions for IN-1K. For instance, RepLKNet-31B achieves only 0.9% accuracy (ImageNet-1K has only 1000 classes in total) beyond a resolution of 640x640, indicating complete model failure. Such demonstrations are significantly detached from practical applications.
>    * At such large resolutions for visualization, the blocky artifacts on ERF become as small as individual pixels, making them difficult to perceive. Please refer to the visualization results on our GitHub homepage and in our paper for more details.
> 2. **Attention Visualization**: We do not employ the CLS token but use the query at the center of the image for visualization. The specific methodology and formulas are thoroughly explained beneath Figure 7 in our paper.

Thank you, sir. But what I drew was not satisfactory.

**Comment by DaiShiResearch** [comment]
You might try using more images for ERF visualization. In our paper, we used 5000 images to reduce the bias from the content of each image and to provide more statistical significance.

**Comment by Fortuneteller6** [comment]
> You might try using more images for ERF visualization. In our paper, we used 5000 images to reduce the bias from the content of each image and to provide more statistical significance.

Thank you very much for your prompt reply, sir. I will try again later.

**Comment by JuergenZhang** [comment]
Hi, thank you for the amazing work on TransNeXt! I have a question regarding the attention visualization, particularly how it works with overlapping patches.

In the paper, you mentioned that TransNeXt uses overlapping patches through the OverlapPatchEmbed class, unlike the standard ViT that uses non-overlapping patches. The issue I'm facing is that in the DINO-based attention visualization code, it assumes that the patch size can evenly divide the original image size. However, since TransNeXt uses overlapping patches, this assumption doesn't hold anymore.

Here’s my understanding of the situation:

In DINO's visualization, patches are non-overlapping, and the original image size is evenly divisible by the patch size, which makes the attention map easily align with the image.

In TransNeXt, the overlapping patches are created using a convolutional layer with a specified patch size and stride. Since these patches overlap, the size of the output feature map after patch embedding (H, W) doesn’t necessarily divide evenly into the original image size. This breaks the assumption in DINO’s visualization code that requires even division.

My concern is that directly using DINO’s visualization method might result in misaligned attention maps due to the different way patches are handled. To solve this, I believe the attention map generation needs to take into account the new dimensions (H, W) produced by OverlapPatchEmbed, rather than relying on the original image dimensions.

Could you provide any guidance or adjustments needed to adapt the visualization method for overlapping patches? Specifically, I’m curious about how to adjust the attention map computation so that it works with overlapping patches.
